// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401132929_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("WebApplication1.Data.Entities.PriceAlertSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAlertedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThresholdPercent")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackedPoolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackedPoolId");

                    b.HasIndex("TelegramUserId", "TrackedPoolId")
                        .IsUnique();

                    b.ToTable("PriceAlertSubscriptions");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.TelegramChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingPoolAddress")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("TelegramChatSessions");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.TelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.TrackedPool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LastKnownInversePrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastKnownPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastKnownTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPolledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token0Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token0Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token1Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token1Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoolAddress")
                        .IsUnique();

                    b.ToTable("TrackedPools");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.PriceAlertSubscription", b =>
                {
                    b.HasOne("WebApplication1.Data.Entities.TelegramUser", "TelegramUser")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Data.Entities.TrackedPool", "TrackedPool")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TrackedPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");

                    b.Navigation("TrackedPool");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.TelegramChatSession", b =>
                {
                    b.HasOne("WebApplication1.Data.Entities.TelegramUser", "TelegramUser")
                        .WithOne("ChatSession")
                        .HasForeignKey("WebApplication1.Data.Entities.TelegramChatSession", "TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.TelegramUser", b =>
                {
                    b.Navigation("ChatSession");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.TrackedPool", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
